### ISSUE TITLE
different behaviour on windows and linux

### ISSUE THREAD

**Issue by hartytp** [m-labs/sipyco#20]
The underlying issue here seems to be differences in how windows and linux treat command line arguments (see https://stackoverflow.com/questions/43955754/argparse-is-adding-quotes-to-a-string-in-python-on-windows-environment).

To see how this manifests, consider the following snippet
```python
import argparse
import sys


parser = argparse.ArgumentParser()
parser.add_argument("args", metavar="ARGS", nargs=argparse.REMAINDER,
                    help="arguments")
args = parser.parse_args()

print(sys.version_info)
print(args.args, [type(arg) for arg in args.args])
```

which we run with `python -m arg_tst '1234'`.

On windows that gives 
```
sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
["'1234'"] [<class 'str'>]
```

On linux
```
python -m arg_tst '1234'
sys.version_info(major=3, minor=9, micro=1, releaselevel='final', serial=0)
['1234'] [<class 'str'>]
```

Note the extra quotation marks around the number on windows.

This becomes annoying when the using the `call` action because the individual arguments are `eval`d here https://github.com/m-labs/sipyco/blob/84aa40e87043dcbf9f6fc6962eed3f67dbfba623/sipyco/sipyco_rpctool.py#L58

On windows, specifying a string argument with normal quotations results in a string argument being passed to the called method. On linux, strings of numbers will be cast into integers, which may upset the called method.

Note that the behaviour is different in `interactive` mode, where the arguments aren't `eval`d individually https://github.com/m-labs/sipyco/blob/84aa40e87043dcbf9f6fc6962eed3f67dbfba623/sipyco/sipyco_rpctool.py#L82

This behavioural difference between windows and linux and `call` / `interactive` modes is a bit of a footgun which could be improved on.

Suggestions for a remedy?

**Comment by sbourdeauducq** [comment]
That's simply because most Linux shells do not make a difference between ``'1234'`` and ``1234`` and just pass the string ``1234`` to the program in both cases. ``'`` is useful to e.g. pass command-line arguments that contain spaces. By contrast Windows ``cmd`` does not interpret ``'``.
You would see this behavior with running any Linux program, including simple commands such as ``cp`` and ``ls``.
If you want to pass ``'`` into a command-line argument with Linux shells, you need to escape it with ``\``.
MSYS2 which will be the only supported installation method with NAC3 ARTIQ (version 8 probably) does not have the discrepancy and implements the Linux behavior.
![image](https://user-images.githubusercontent.com/720864/162697513-9adb005d-2863-42ec-bda0-94aa3ef975ad.png)
